insert into PENALTY (ACCRUAL_AMOUNT, AMOUNT_TO_BE_PAID, ARTICLE_OF_THE_ADMINISTRATIVE_CODE, DATE_OF_THE_RESOLUTION,
                     RESOLUTION_NUMBER, TAXPAYER_IDENTIFICATION_NUMBER, VEHICLE_CERTIFICATE)
values (12.33, 14.55, 'test', '2023-01-03', 'test1', 'test2', 'test3');
